version: '5.0.{build}'
skip_tags: true
image: Visual Studio 2022
configuration: Release
install:
  - ps: mkdir -Force ".\build\" | Out-Null
  - ps: dotnet --info
build_script:
- ps: .\build.ps1
test: false
artifacts:
  - path: artifacts/*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 8ToTzkKMHYAKVqO3iGolSEIcZFRWsKiRglu8t2WjSe4Tg9Oj3Hg9s5A1uAAg+uRe
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
